import {Flower} from "./Flowers";

export const MOCK_FLOWERS = [
    new Flower({
        id: 1,
        name: 'Tulip',
        season: 'Spring',
        imageUrl: 'https://static.wikia.nocookie.net/hmwikia/images/a/a8/PoOTTulip.png/revision/latest?cb=20220328073033',
        honeyType: 'Honey Hive',
    }),
    new Flower({
        id: 2,
        name: 'Nemophila',
        season: 'Spring',
        imageUrl: '',
        honeyType: 'Honey Hive',
    }),
    new Flower({
        id: 3,
        name: 'Pansy',
        season: 'Spring',
        imageUrl: '',
        honeyType: 'Honey Hive',
    }),
    new Flower({
        id: 4,
        name: 'Hibiscus',
        season: 'Summer',
        imageUrl: '',
        honeyType: 'Honey Hive',
    }),
    new Flower({
        id: 5,
        name: 'Petunia',
        season: 'Summer',
        imageUrl: '',
        honeyType: 'Honey Hive',
    }),
    new Flower({
        id: 6,
        name: 'Marigold',
        season: 'Summer',
        imageUrl: '',
        honeyType: 'Honey Hive',
    }),
    new Flower({
        id: 7,
        name: 'RoseMum',
        season: 'Fall',
        imageUrl: '',
        honeyType: 'Honey Hive',
    }),
    new Flower({
        id: 8,
        name: 'Cineraria',
        season: 'Winter',
        imageUrl: '',
        honeyType: 'Honey Hive',
    }),
    new Flower({
        id: 9,
        name: 'Primrose',
        season: 'Winter',
        imageUrl: '',
        honeyType: 'Honey Hive',
    }),
    new Flower({
        id: 10,
        name: 'Buttercup',
        season: 'Spring',
        imageUrl: '',
        honeyType: 'Honeycomb Hive',
    }),
    new Flower({
        id: 11,
        name: 'Sunflower',
        season: 'Summer',
        imageUrl: '',
        honeyType: 'Honeycomb Hive',
    }),
    new Flower({
        id: 12,
        name: 'Clematis',
        season: 'Fall',
        imageUrl: '',
        honeyType: 'Honeycomb Hive',
    }),
    new Flower({
        id: 13,
        name: 'Begonia',
        season: 'Winter',
        imageUrl: '',
        honeyType: 'Honeycomb Hive',
    }),
    new Flower({
        id: 14,
        name: 'Black Pansy',
        season: 'Spring',
        imageUrl: '',
        honeyType: 'Worker Hive',
    }),
    new Flower({
        id: 15,
        name: 'Lily',
        season: 'Summer',
        imageUrl: '',
        honeyType: 'Worker Hive',
    }),
    new Flower({
        id: 15,
        name: 'Daisy',
        season: 'Fall',
        imageUrl: '',
        honeyType: 'Worker Hive',
    }),
    new Flower({
        id: 16,
        name: 'Black Rose',
        season: 'Fall',
        imageUrl: '',
        honeyType: 'Worker Hive',
    }),
    new Flower({
        id: 17,
        name: 'Campanula',
        season: 'Winter',
        imageUrl: '',
        honeyType: 'Worker Hive',
    }),
    new Flower({
        id: 18,
        name: 'Hellebore',
        season: 'Winter',
        imageUrl: '',
        honeyType: 'Royal Hive',
    }),
]